version: '3.8'

services:
  database:
    image: postgres:15
    container_name: social_network_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admi1
      POSTGRES_DB: social_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
